export const DARK_MODE_SET = "DARK_MODE_SET";
export const NORMAL_MODE_SET = "NORMAL_MODE_SET";
export const DEV_MODE_SET = "DEV_MODE_SET";
export const PROD_MODE_SET = "PROD_MODE_SET";
export const TOAST_CLEAR = "TOAST_CLEAR";
export const TOAST_SET_VALUE = "TOAST_SET_VALUE";

export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const SEND_NOTIFICATION_START = "SEND_NOTIFICATION_START";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAIL = "SEND_NOTIFICATION_FAIL";

export const USER_REGISTRATION_START = "USER_REGISTRATION_START";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAIL = "LOAD_COMMENTS_FAIL";

export const ALL_COMMENTS_START = "ALL_COMMENTS_START";
export const ALL_COMMENTS_SUCCESS = "ALL_COMMENTS_SUCCESS";
export const ALL_COMMENTS_FAIL = "ALL_COMMENTS_FAIL";

export const REPLY_COMMENTS_START = "REPLY_COMMENTS_START";
export const REPLY_COMMENTS_SUCCESS = "REPLY_COMMENTS_SUCCESS";
export const REPLY_COMMENTS_FAIL = "REPLY_COMMENTS_FAIL";

export const COMMENT_UPDATE_START = "COMMENT_UPDATE_START";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAIL = "COMMENT_UPDATE_FAIL";



